export const CAT_REQUEST = 'CAT_REQUEST';
export const CAT_SUCCESS = 'CAT_SUCCESS';
export const CAT_FAIL = 'CAT_FAIL';
export const CAT_LIST_REQUEST = 'CAT_LIST_REQUEST';
export const CAT_LIST_SUCCESS = 'CAT_LIST_SUCCESS';
export const CAT_LIST_FAIL = 'CAT_LIST_FAIL';
export const CREATE_CAT_ONLY_REDUX= 'CREATE_CAT_ONLY_REDUX';
  
