export const COLOR_LIST_REQUEST = 'COLOR_LIST_REQUEST';
export const COLOR_LIST_SUCCESS = 'COLOR_LIST_SUCCESS';
export const COLOR_LIST_FAIL = 'COLOR_LIST_FAIL';

export const COLOR_DETAILS_REQUEST = 'COLOR_DETAILS_REQUEST';
export const COLOR_DETAILS_SUCCESS = 'COLOR_DETAILS_SUCCESS';
export const COLOR_DETAILS_FAIL = 'COLOR_DETAILS_FAIL';

export const COLOR_SAVE_REQUEST = 'COLOR_SAVE_REQUEST';
export const COLOR_SAVE_SUCCESS = 'COLOR_SAVE_SUCCESS';
export const COLOR_SAVE_FAIL = 'COLOR_SAVE_FAIL';

export const COLOR_DELETE_REQUEST = 'COLOR_DELETE_REQUEST';
export const COLOR_DELETE_SUCCESS = 'COLOR_DELETE_SUCCESS';
export const COLOR_DELETE_FAIL = 'COLOR_DELETE_FAIL'