export const DOORS_LIST_REQUEST = 'DOORS_LIST_REQUEST';
export const DOORS_LIST_SUCCESS = 'DOORS_LIST_SUCCESS';
export const DOORS_LIST_FAIL = 'DOORS_LIST_FAIL';

export const DOORS_MAIN_LIST_REQUEST = 'DOORS_MAIN_LIST_REQUEST';
export const DOORS_MAIN_LIST_SUCCESS = 'DOORS_MAIN_LIST_SUCCESS';
export const DOORS_MAIN_LIST_FAIL = 'DOORS_MAIN_LIST_FAIL';
export const DOORS_MAIN_LIST_RESET = 'DOORS_MAIN_LIST_RESET';


export const DOOR_DETAILS_REQUEST = 'DOOR_DETAILS_REQUEST';
export const DOOR_DETAILS_SUCCESS = 'DOOR_DETAILS_SUCCESS';
export const DOOR_DETAILS_FAIL = 'DOOR_DETAILS_FAIL';

export const DOOR_SAVE_REQUEST = 'DOOR_SAVE_REQUEST';
export const DOOR_SAVE_SUCCESS = 'DOOR_SAVE_SUCCESS';
export const DOOR_SAVE_FAIL = 'DOOR_SAVE_FAIL';

export const DOOR_DELETE_REQUEST = 'DOOR_DELETE_REQUEST';
export const DOOR_DELETE_SUCCESS = 'DOOR_DELETE_SUCCESS';
export const DOOR_DELETE_FAIL = 'DOOR_DELETE_FAIL';

export const DOOR_REVIEW_SAVE_REQUEST = 'DOOR_REVIEW_SAVE_REQUEST';
export const DOOR_REVIEW_SAVE_SUCCESS = 'DOOR_REVIEW_SAVE_SUCCESS';
export const DOOR_REVIEW_SAVE_FAIL = 'DOOR_REVIEW_SAVE_FAIL';
export const DOOR_REVIEW_SAVE_RESET = 'DOOR_REVIEW_SAVE_RESET';

export const  LOAD_CATEGORY = 'LOAD_CATEGORY';
export const  LOAD_SORT_BY= 'LOAD_SORT_BY';