export const PENS_LIST_REQUEST = 'PENS_LIST_REQUEST';
export const PENS_LIST_SUCCESS = 'PENS_LIST_SUCCESS';
export const PENS_LIST_FAIL = 'PENS_LIST_FAIL';

export const PEN_DETAILS_REQUEST = 'PEN_DETAILS_REQUEST';
export const PEN_DETAILS_SUCCESS = 'PEN_DETAILS_SUCCESS';
export const PEN_DETAILS_FAIL = 'PEN_DETAILS_FAIL';

export const PEN_SAVE_REQUEST = 'PEN_SAVE_REQUEST';
export const PEN_SAVE_SUCCESS = 'PEN_SAVE_SUCCESS';
export const PEN_SAVE_FAIL = 'PEN_SAVE_FAIL';

export const PEN_DELETE_REQUEST = 'PEN_DELETE_REQUEST';
export const PEN_DELETE_SUCCESS = 'PEN_DELETE_SUCCESS';
export const PEN_DELETE_FAIL = 'PEN_DELETE_FAIL';

export const PEN_REVIEW_SAVE_REQUEST = 'PEN_REVIEW_SAVE_REQUEST';
export const PEN_REVIEW_SAVE_SUCCESS = 'PEN_REVIEW_SAVE_SUCCESS';
export const PEN_REVIEW_SAVE_FAIL = 'PEN_REVIEW_SAVE_FAIL';
export const PEN_REVIEW_SAVE_RESET = 'PEN_REVIEW_SAVE_RESET';

export const  LOAD_CATEGORY = 'LOAD_CATEGORY';
export const  LOAD_SORT_BY= 'LOAD_SORT_BY';